services:
  ai-dev:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: ai-dev-container
    image: ai-project
    env_file:
      - .env
    stdin_open: true
    tty: true
    volumes:
      - .:/workspace:cached
      - pip-cache:/root/.cache/pip
      - uv-cache:/root/.cache/uv
    ports:
      - "8888:8888"
      - "8787:8787"
    shm_size: '2gb'
    restart: unless-stopped
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
volumes:
  pip-cache:
  uv-cache:
